### PR TITLE
Setting camera target to most negative number to handle arbitrary large maps

### PR DESCRIPTION
**Pull request by aaronchongth**
## What's new

* Tweak camera target to most negative number to better accommodate almost-orthogonal view for extremely large maps
* refactored camera control to prevent creation of camera every time zoom changes

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

### CODE REVIEW

**Review by koonpeng — COMMENTED** [review]
Not sure what this affects, but if we know the size of the map, then could we calculate this dynamically? If not then is there value to make this an app-config?

**Comment by aaronchongth** [comment]
This changes the 3D position that the camera points towards, raising it to a large negative number implies that the camera will almost always be pointing down vertically, no matter where the camera is moved to in 3D space. This helps mimic an orthogonal view.

Although this value falls under the category of bigger-is-better, there's no harm in using the scene size to calculate it dynamically I guess.

I've also refactored the camera controls a little to reduce repeated construction of cameras and its controller

**Review by koonpeng — CHANGES_REQUESTED** [review]
Sounds like there is no harm in having a smaller value? If so then let's revert the dynamic calculation change.

**Comment by aaronchongth** [comment]
As explained the purpose of these changes in DM

**Review by koonpeng — APPROVED** [review]

**Pull request merged**
