### PR TITLE
more rows and sort cancelled task

### PR DESCRIPTION
**Pull request by ChawinTan**
Signed-off-by: ChawinTan <chawin15@gmail.com>

## What's new

- increase task rows from 10 to 20
- shift cancelled task to the back

## Self-checks

- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

### CODE REVIEW

**Comment by tanyouliang95** [comment]
Hi @ChawinTan Thanks for the fast fix. Should we merge this into `main` instead since this will also be common non-blocking feature? (if you think this is suitable)

Also other than shifting `Canceled`, can we also pushback `Failed` and `Completed` tasks?

**Comment by koonpeng** [comment]
Note that a row count of 10 is chosen because one of the design goal of the wireframe is to minimize scrolling. I think a row count of 20 would almost always end up with a scroll bar.

The sorting is also part of the design, to sort by priority first then start time.

Let's consult with @vallq and @codebot to make sure that this is the direction we want to go.

**Comment by ChawinTan** [comment]
My thoughts were that this feature is for debugging purposes for the demo only, so I think we should keep it to the throwaway/demo branch.

**Comment by koonpeng** [comment]
> My thoughts were that this feature is for debugging purposes for the demo only, so I think we should keep it to the throwaway/demo branch.

Yeah, but I'm not sure about demoing changes that are in conflict with the design decisions we have. We would be demoing something that is not representation of the actual product we are "selling". Changes like these should go directly to the main branch, after we agree that these changes are acceptable to the design decisions we had.

**Review by tanyouliang95 — APPROVED** [review]
Yes understand. Since these design decisions are not finalized, we will only merge it into `throwaway/demo, and we will review this as time comes.

Anyway, tested it and it works as described. Thanks a lot!!

**Comment by Yadunund** [comment]
I'm on the latest `throwaway/demo` but the tasks are not sorted 🤔 
image

**Comment by ChawinTan** [comment]
My changes got removed probably during merging. Will make a pr now.

**Pull request merged**
