### PR TITLE
example-deployment:Fixed reporting auth uid problem

### PR DESCRIPTION
**Pull request by matiasbavera**
pre-requisite https://github.com/open-rmf/rmf-web/pull/357

Set reporting client scope and assigned that scope to the client. This fixed the reporting-server authentication issue on the kubernetes cluster.
Signed-off-by: Matias Bavera <matiasbavera@gmail.com>

## Self-checks

- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

### CODE REVIEW

**Comment by cnboonhan** [comment]
Hello, encountered error with missing ConfigMap, i think you might need to add something like this:
`kubectl create configmap reporting-server-config --from-file=reporting_server_config.py -o=yaml --dry-run=client | kubectl apply -f -`
after [this](https://github.com/matiasbavera/romi-dashboard/blob/fix/addReportingUIDConfig/example-deployment/deploy.sh#L82) line

**Review by cnboonhan — CHANGES_REQUESTED** [review]
Hello, encountered error with missing ConfigMap, i think you might need to add something like this:
kubectl create configmap reporting-server-config --from-file=reporting_server_config.py -o=yaml --dry-run=client | kubectl apply -f -
after [this](https://github.com/matiasbavera/romi-dashboard/blob/fix/addReportingUIDConfig/example-deployment/deploy.sh#L82) line

apart from that, build works!

**Comment by matiasbavera** [comment]
> Hello, encountered error with missing ConfigMap, i think you might need to add something like this:
> `kubectl create configmap reporting-server-config --from-file=reporting_server_config.py -o=yaml --dry-run=client | kubectl apply -f -`
> after [this](https://github.com/matiasbavera/romi-dashboard/blob/fix/addReportingUIDConfig/example-deployment/deploy.sh#L82) line
> 
> apart from that, build works!

Hi! yes, it's in this PR https://github.com/open-rmf/rmf-web/pull/357

**Review by cnboonhan — APPROVED** [review]
once this PR https://github.com/open-rmf/rmf-web/pull/357 is merged, this PR should work fine. LGTM!

**Pull request merged**
