### PR TITLE
Fix/frontend dashboard misc fixes

### PR DESCRIPTION
**Pull request by youliangtan**
PR originated from https://github.com/open-rmf/rmf-web/pull/603

Fixed some miscellaneous front-end components
 - Limit battery percentage 2 decimals
 - set default traj length to 5 mins (prev was 1 min, is too short for task with longer duration)
 - Fix incorrect "finish time" for task displayed on robot tab
 - Add `category` column to the task table on tasks tab. According to user feedback, this is useful, especially for generic "compose tasks".
 - Fix task progress bar incorrect calculation
 - (Add-on) fix buggy place lists for loop task submission form

### CODE REVIEW

**Review by koonpeng — COMMENTED** [review]
> Fix incorrect "finish time" for task displayed on robot tab
> Fix task progress bar incorrect calculation

These 2 are also fixed in the window system PR, @aaronchongth which PR should we merge first?

**Comment by aaronchongth** [comment]
I think https://github.com/open-rmf/rmf-web/pull/623 should be merged first. This PR is small enough that changes would be much easier to review and test. Thanks!

**Comment by youliangtan** [comment]
@aaronchongth this is ready for review.

**Review by aaronchongth — APPROVED** [review]
Thanks for the various fixes, @youliangtan! I've taken the liberty of removing the unneeded version bumps, and fixed a text finding test for battery percentage, since it has been fixed to 2 decimal places. LGTM!

**Pull request merged**
