### PR TITLE
Dashboard: Fix dashboard does not get icons from kubernetes cluster

### PR DESCRIPTION
**Pull request by matiasbavera**
Signed-off-by: Matias Bavera <matiasbavera@gmail.com>

1. run the `example-deployment/get-icon.sh` script to populate the  ws/rmf-web/packages/dashboard` with the icons.
2. build the dashboard's docker.

## Self-checks

- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

### CODE REVIEW

**Comment by cnboonhan** [comment]
thank you for your help :bow: 

i think there might be a few differences in how we are using rmf-web and the script,

could it be possible to use environment variable to specify paths for the `rmf-web` workspace? we put rmf-web in $HOME, not in `ws`.

In addition, we are using custom icons not available online, how do we modify the .resources file accordingly?

**Comment by koonpeng** [comment]
I believe the example deployment git clones the rmf sources as part of the instructions, so you can point to script to the rmf directories via relative paths.

> i think there might be a few differences in how we are using rmf-web and the script,
> could it be possible to use environment variable to specify paths for the rmf-web workspace? we put rmf-web in $HOME, not in ws.
> In addition, we are using custom icons not available online, how do we modify the .resources file accordingly?

In that case, I don't think you should be using the example scripts, you can run the setup from the dashboard before building it as part of your deployment script.

**Comment by matiasbavera** [comment]
> I believe the example deployment git clones the rmf sources as part of the instructions, so you can point to script to the rmf directories via relative paths.

You mean by using the js "ament"? 

> In that case, I don't think you should be using the example scripts, you can run the setup from the dashboard before building it as part of your deployment script.

Yeah, sounds good. So there is no need for the get-icons-locally script then. So the deploy script should show the resources prompt then? 

I'll create a new issue with this and let's merge just the icon fix then

**Review by koonpeng — APPROVED** [review]
If this is just the icon fix, I think it can go into the main branch.

**Pull request merged**
