### PR TITLE
feat: zoom into robot on the map when a robot is selected

### PR DESCRIPTION
**Pull request by koonpeng**
## What's new

Zoom into robot on the map when a robot is selected

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

### CODE REVIEW

**Review by youliangtan — CHANGES_REQUESTED** [review]
Noticed some merge conflicts when merging `main` into this branch.

**Comment by youliangtan** [comment]
Also side quest: in another demo project, we have a way larger map than the classic `office` world map. Using the new windowing system ui, the floorplan will get zoomed in to a blank corner when using the dashboard. (user will need an extra step to zoom out, and "size-fit" the map). Will that be good if we include the "size fit" floorplan feature into this pr? or we can also open this as a separate pr.

**Comment by mayman99** [comment]
solved the merge conflicts, but before and after solving the conflicts the zoom doesn't behave as expected

**Comment by mayman99** [comment]
solved the merge conflicts, but before and after solving the conflicts the zoom doesn't behave as expected

**Comment by aaronchongth** [comment]
https://user-images.githubusercontent.com/5383623/211130902-89583859-6c64-4468-853a-f9793cdf72b2.mp4

**Pull request merged**
