### PR TITLE
add demo logo path to appbar

### PR DESCRIPTION
**Pull request by vallq**
Signed-off-by: vallq <val@openrobotics.org>

## What's new
This requires `rmf_web's` throwaway branch to be updated with the latest `main` branch fix by Matias (#362) and for the `rmf_demos` repo to be on `throwaway/demos` as well.

Following the dashboard's README installation instructions, 
after running `lerna bootstrap`, to ensure that icons are retrieved, 
run `npm run setup`
image
This interface should appear, pick the options 2, 3 and the default office world map

image
`public` directory will be updated with the icons 
Running the dashboard with `npm run start` should have the set logo

## Discussion
This feels a little hacky like a quick fix. Not sure if there is a better way to implement this for future development.

### CODE REVIEW

**Comment by vallq** [comment]
Update: https://github.com/open-rmf/rmf_demos/pull/48

**Comment by matiasbavera** [comment]
Added a resource manager for this feature. If there is no icons it defaults to the rmf health icon

**Comment by vallq** [comment]
Related PR: https://github.com/open-rmf/rmf_demos/pull/50/
I added the icons for each world map in `rmf_dashboard_resources`, running `npm run setup` to change the resources will alter the header's logo accordingly. 
To change the logo locally, remove the existing `logo.png` in the `public/assets/branding/demo` folder and replace it with a new `logo.png`
image

Starting the dashboard with different resources set should show the different logos
image
image
image
image

**Review by Yadunund — APPROVED** [review]
Tested and works great. Thanks @vallq

**Pull request merged**
