### PR TITLE
throwaway-demo/robot panel mods

### PR DESCRIPTION
**Pull request by ChawinTan**
## What's new

https://user-images.githubusercontent.com/29136440/119939750-e44fe780-bfc0-11eb-962f-8d8f05499af6.mp4

Related Issue: #353

- fixed the ordering of the tasks
- use a custom hook with setInterval to continuously poll and update tasks and robots to update the assigned tasks and progress bar

Intervals are set to 3 seconds

## Self-checks

- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

### CODE REVIEW

**Comment by Yadunund** [comment]
@ChawinTan , when testing in simulation, the robot card is being updated accurately. However, when I run a live demo, that is not the case (the robot card does not even get populated with its current task and there aren't any updates).

**Review by koonpeng — APPROVED** [review]
Auto approve merges to throwaway branch.

**Comment by Yadunund** [comment]
@ChawinTan should we fix the pagination problem in this PR?

**Comment by ChawinTan** [comment]
I think I will create another pr for a "proper" fix since #348 has been merged. If everything works for you, do go ahead and merge this pr.

**Comment by Yadunund** [comment]
I'll merge this in for now as the auto update is working. But for the demo would require the "proper" fix as well.

**Pull request merged**
