### PR TITLE
support multiple subscriptions

### PR DESCRIPTION
**Pull request by koonpeng**
## What's new

Keep tracks of number of ongoing subscriptions to a room so that `unsubscribe` is emitted only when the last subscriber has unsubscribed.

## Self-checks

- [ ] I have prototyped this new feature (if necessary) on Figma 
- [ ] I'm familiar with and follow this [Typescript guideline](https://basarat.gitbook.io/typescript/styleguide)
- [ ] I added unit-tests for new components
- [ ] I tried testing edge cases
- [ ] I tested the behavior of the components that interact with the backend, with an e2e test

### CODE REVIEW

**Comment by koonpeng** [comment]
@cnboonhan This targets main, I will update `prototype/tasksv2-2` once this is merged.

**Comment by mayman99** [comment]
So this means at the moment if we have two subscribers, when one of them unsubscribe the server will not be sending anything to the other not-dead subscriber?

**Comment by cnboonhan** [comment]
i think that is the case yes

**Comment by cnboonhan** [comment]
I tried this out with this simple script. I was expecting no more door state updates ( since we subscribe twice and then unsubscribe both listeners. However, the second unsubscribe fails.

RMF:
```
ros2 launch rmf_demos_ign office.launch.xml headless:=1 use_sim_time:=false finishing_request:=charge
rmf_api_server
```
Script listen.ts
```
import { SioClient } from '../lib';

const client = new SioClient('http://localhost:8000');
const l1 = client.subscribeDoorState("coe_door", console.log)
const l2 = client.subscribeDoorState("coe_door", console.log)

client.unsubscribe(l1)
client.unsubscribe(l2)
```
Run script
```
DEBUG=rmf-client ts-node listen.ts
```

Output:
```
(rmf-web) cnboonhan@HpPersonal [100]:~/workspaces/rmf_ws/src/rmf-web/packages/api-client/examples (support-multi-subscription) $ DEBUG=rmf-client ts-node listen.ts
  rmf-client subscribed to /doors/coe_door/state +0ms
  rmf-client reusing previous subscription to /doors/coe_door/state +1ms
  rmf-client LISTENERS +1ms
  rmf-client Map(1) { [Function: log] => '/doors/coe_door/state' } +0ms
  rmf-client skipping unsubscribe to /doors/coe_door/state because there are still 1 subscribers +1ms
  rmf-client LISTENERS +0ms
  rmf-client Map(0) {} +0ms
  rmf-client fail to unsubscribe, listener not found in list of subscriptions +0ms
{
  door_time: { sec: 83, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}
{
  door_time: { sec: 84, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}
{
  door_time: { sec: 85, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}
{
  door_time: { sec: 86, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}
```

**Review by cnboonhan — COMMENTED** [review]
I tried this out with this simple script. I was expecting no more door state updates ( since we subscribe twice and then unsubscribe both listeners. However, the second unsubscribe fails.

RMF:

ros2 launch rmf_demos_ign office.launch.xml headless:=1 use_sim_time:=false finishing_request:=charge
rmf_api_server
Script packages/api-client/examples/listen.ts

import { SioClient } from '../lib';

const client = new SioClient('http://localhost:8000');
const l1 = client.subscribeDoorState("coe_door", console.log)
const l2 = client.subscribeDoorState("coe_door", console.log)

client.unsubscribe(l1)
client.unsubscribe(l2)
Run script

DEBUG=rmf-client ts-node listen.ts
Output ( I added debug output to print out the contents of this._listenerRoom )

(rmf-web) cnboonhan@HpPersonal [100]:~/workspaces/rmf_ws/src/rmf-web/packages/api-client/examples (support-multi-subscription) $ DEBUG=rmf-client ts-node listen.ts
  rmf-client subscribed to /doors/coe_door/state +0ms
  rmf-client reusing previous subscription to /doors/coe_door/state +1ms
  rmf-client LISTENERS +1ms
  rmf-client Map(1) { [Function: log] => '/doors/coe_door/state' } +0ms
  rmf-client skipping unsubscribe to /doors/coe_door/state because there are still 1 subscribers +1ms
  rmf-client LISTENERS +0ms
  rmf-client Map(0) {} +0ms
  rmf-client fail to unsubscribe, listener not found in list of subscriptions +0ms
{
  door_time: { sec: 83, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}
{
  door_time: { sec: 84, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}
{
  door_time: { sec: 85, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}
{
  door_time: { sec: 86, nanosec: 230000000 },
  door_name: 'coe_door',
  current_mode: { value: 0 }
}

**Comment by koonpeng** [comment]
Yeah, this is because we are using the callbacks to track subscriptions, we can use a subscription id instead.

**Comment by koonpeng** [comment]
@cnboonhan fixed the mentioned behavior and added tests

**Review by cnboonhan — APPROVED** [review]
Looks great to me! ( I have not been able to test further but i believe it works well, as the tests are quite similar to my more basic ones ) Thank you!

**Pull request merged**
